apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rp-api-ingress-public
  annotations:
    ingress.bluemix.net/ALB-ID: "public-cr3270956cbe4147c392dcc54c2f3af335-alb1"
spec:
  rules:
  - host: rp.dsw-im-cloud-public-dev.us-south.containers.appdomain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-rs
          servicePort: 80